
import re

def convert_to_regexp(val: str):
    reg_exp_str = re.escape(str(val)).replace('%', '.*')
    reg_exp = re.compile(f"\\b{reg_exp_str}\\b", re.IGNORECASE)

    return {'$regex': reg_exp}



custom_filter_options = {
    '$or':[
{
        '$or': [
            {'title': convert_to_regexp('Health')},
            {'title': convert_to_regexp('Auditor')},
            {'department': convert_to_regexp('Health')},
            {'title': convert_to_regexp('Human Services')},
            {'department': convert_to_regexp('Human Services')},
            {'title': convert_to_regexp('Environmental')},
            {'department': convert_to_regexp('Environmental')},
            {'title': convert_to_regexp('Mental')},
            {'department': convert_to_regexp('Mental')},
            {'title': convert_to_regexp('Medical')},
            {'department': convert_to_regexp('Medical')},
            {'title': convert_to_regexp('Disease')},
            {'department': convert_to_regexp('Disease')},
            {'title': convert_to_regexp('Epidemiologist')},
            {'department': convert_to_regexp('Epidemiologist')},
            {'title': convert_to_regexp('Social Services')},
            {'department': convert_to_regexp('Social Services')},
            {'title': convert_to_regexp('Nurse')},
            {'department': convert_to_regexp('Nurse')}
        ],
    },
{
        '$or': [
            {'title': convert_to_regexp('Public Works')},
            {'department': convert_to_regexp('Public Works')},
            {'title': convert_to_regexp('Transportation')},
            {'department': convert_to_regexp('Transportation')},
            {'title': convert_to_regexp('Environmental')},
            {'department': convert_to_regexp('Environmental')},
            {'title': convert_to_regexp('Civil')},
            {'department': convert_to_regexp('Civil')},
            {'title': convert_to_regexp('Engineer')},
            {'department': convert_to_regexp('Engineer')},
            {'title': convert_to_regexp('Water')},
            {'department': convert_to_regexp('Water')},
            {'title': convert_to_regexp('Street')},
            {'department': convert_to_regexp('Street')},
            {'title': convert_to_regexp('Fleet')},
            {'department': convert_to_regexp('Fleet')},
            {'title': convert_to_regexp('Traffic')},
            {'department': convert_to_regexp('Traffic')},
            {'title': convert_to_regexp('Highway')},
            {'department': convert_to_regexp('Highway')},
            {'title': convert_to_regexp('Foreman')},
            {'department': convert_to_regexp('Foreman')},
            {'title': convert_to_regexp('Facilities')},
            {'department': convert_to_regexp('Facilities')}
        ],
    },
{
        '$or': [
            {'title': convert_to_regexp('Parks')},
            {'department': convert_to_regexp('Parks')},
            {'title': convert_to_regexp('Ranger')},
            {'department': convert_to_regexp('Ranger')},
            {'title': convert_to_regexp('Recreation')},
            {'department': convert_to_regexp('Recreation')},
            {'title': convert_to_regexp('Landscape')},
            {'department': convert_to_regexp('Landscape')},
            {'title': convert_to_regexp('Park Maintenance')},
            {'department': convert_to_regexp('Park Maintenance')},
            {'title': convert_to_regexp('Trees')},
            {'department': convert_to_regexp('Trees')},
            {'title': convert_to_regexp('Recreation')},
            {'department': convert_to_regexp('Recreation')},
            {'title': convert_to_regexp('Conservation')},
            {'department': convert_to_regexp('Conservation')},
            {'title': convert_to_regexp('Tourism')},
            {'department': convert_to_regexp('Tourism')},
            {'title': convert_to_regexp('Forestry')},
            {'department': convert_to_regexp('Forestry')},
            {'title': convert_to_regexp('Outdoor')},
            {'department': convert_to_regexp('Outdoor')},
            {'title': convert_to_regexp('Public Spaces')},
            {'department': convert_to_regexp('Public Spaces')},
            {'title': convert_to_regexp('Natural Resources')},
            {'department': convert_to_regexp('Natural Resources')}
        ],
    },
{
        '$or': [
            {'title': convert_to_regexp('Mayor')},
            {'department': convert_to_regexp('Mayor')},
            {'title': convert_to_regexp('Council Member')},
            {'department': convert_to_regexp('Council Member')},
            {'title': convert_to_regexp('Senator')},
            {'department': convert_to_regexp('Senator')},
            {'title': convert_to_regexp('State Representative')},
            {'department': convert_to_regexp('State Representative')},
            {'title': convert_to_regexp('Governor')},
            {'department': convert_to_regexp('Governor')},
            {'title': convert_to_regexp('Sheriff')},
            {'department': convert_to_regexp('Sheriff')},
            {'title': convert_to_regexp('County Clerk')},
            {'department': convert_to_regexp('County Clerk')},
            {'title': convert_to_regexp('Treasurer')},
            {'department': convert_to_regexp('Treasurer')},
            {'title': convert_to_regexp('District Attorney')},
            {'department': convert_to_regexp('District Attorney')},
            {'title': convert_to_regexp('Chairman')},
            {'department': convert_to_regexp('Chairman')},
            {'title': convert_to_regexp('President')},
            {'department': convert_to_regexp('President')},
            {'title': convert_to_regexp('Judge')},
            {'department': convert_to_regexp('Judge')},
            {'title': convert_to_regexp('Alderman')},
            {'department': convert_to_regexp('Alderman')},
            {'title': convert_to_regexp('Supervisor')},
            {'department': convert_to_regexp('Supervisor')},
        ]
    },
{
        '$or': [
            {'title': convert_to_regexp('Commissioner')},
            {'department': convert_to_regexp('Commissioner')},
            {'title': convert_to_regexp('Chairman')},
            {'department': convert_to_regexp('Chairman')},
            {'title': convert_to_regexp('President')},
            {'department': convert_to_regexp('President')},
            {'title': convert_to_regexp('Councilor')},
            {'department': convert_to_regexp('Councilor')},
            {'title': convert_to_regexp('Councilman')},
            {'department': convert_to_regexp('Councilman')},
            {'title': convert_to_regexp('Councilwoman')},
            {'department': convert_to_regexp('Councilwoman')},
            {'title': convert_to_regexp('Supervisor')},
            {'department': convert_to_regexp('Supervisor')},
            {'title': convert_to_regexp('Justice Of The Peace')},
            {'department': convert_to_regexp('Justice Of The Peace')},
            {'title': convert_to_regexp('Assembly Member')},
            {'department': convert_to_regexp('Assembly Member')},
            {'title': convert_to_regexp('Board Of Directors')},
            {'department': convert_to_regexp('Board Of Directors')},
            {'title': convert_to_regexp('Alderman')},
            {'department': convert_to_regexp('Alderman')},
            {'title': convert_to_regexp('Court Member')},
            {'department': convert_to_regexp('Court Member')},
            {'title': convert_to_regexp('Supervisor')},
            {'department': convert_to_regexp('Supervisor')},
            {'title': convert_to_regexp('Majority Leader')},
            {'department': convert_to_regexp('Majority Leader')},
            {'title': convert_to_regexp('Minority Leader')},
            {'department': convert_to_regexp('Minority Leader')},
            {'title': convert_to_regexp('Alderwoman')},
            {'department': convert_to_regexp('Alderwoman')},
            {'title': convert_to_regexp('Township Trustee')},
            {'department': convert_to_regexp('Township Trustee')},
            {'title': convert_to_regexp('Magistrate')},
            {'department': convert_to_regexp('Magistrate')},
            {'title': convert_to_regexp('Judge')},
            {'department': convert_to_regexp('Judge')},
            {'title': convert_to_regexp('Chairwoman')},
            {'department': convert_to_regexp('Chairwoman')}
        ],
    },

    
{
        '$or': [
            {'title': convert_to_regexp('Zoning')},
            {'department': convert_to_regexp('Zoning')},
            {'title': convert_to_regexp('Planning')},
            {'department': convert_to_regexp('Planning')},
            {'title': convert_to_regexp('Urban Development')},
            {'department': convert_to_regexp('Urban Development')},
            {'title': convert_to_regexp('Building')},
            {'department': convert_to_regexp('Building')},
            {'title': convert_to_regexp('Urban Designer')},
            {'department': convert_to_regexp('Urban Designer')},
            {'title': convert_to_regexp('Architectural')},
            {'department': convert_to_regexp('Architectural')},
            {'title': convert_to_regexp('Land Use')},
            {'department': convert_to_regexp('Land Use')},
            {'title': convert_to_regexp('Planner')},
            {'department': convert_to_regexp('Planner')}
        ],
    },
{
        '$or': [
            {'title': convert_to_regexp('Sustainability')},
            {'department': convert_to_regexp('Sustainability')},
            {'title': convert_to_regexp('Climate')},
            {'department': convert_to_regexp('Climate')},
            {'title': convert_to_regexp('Environmental')},
            {'department': convert_to_regexp('Environmental')},
            {'title': convert_to_regexp('Environment')},
            {'department': convert_to_regexp('Environment')},
            {'title': convert_to_regexp('Scientist')},
            {'department': convert_to_regexp('Scientist')},
            {'title': convert_to_regexp('Green')},
            {'department': convert_to_regexp('Green')},
            {'title': convert_to_regexp('Resilience')},
            {'department': convert_to_regexp('Resilience')}
        ],
    },
{
        '$or': [
            {'title': convert_to_regexp('Police Chief')},
            {'department': convert_to_regexp('Police Chief')},
            {'title': convert_to_regexp('Detective')},
            {'department': convert_to_regexp('Detective')},
            {'title': convert_to_regexp('Police')},
            {'department': convert_to_regexp('Police')},
            {'title': convert_to_regexp('Marshal')},
            {'department': convert_to_regexp('Marshal')},
            {'title': convert_to_regexp('Sheriff')},
            {'department': convert_to_regexp('Sheriff')},
            {'title': convert_to_regexp('Police Services')},
            {'department': convert_to_regexp('Police Services')},
            {'title': convert_to_regexp('Patrol')},
            {'department': convert_to_regexp('Patrol')}
        ],
    },
{
        '$or': [
            {'title': convert_to_regexp('Purchasing')},
            {'department': convert_to_regexp('Purchasing')},
            {'title': convert_to_regexp('Procurement')},
            {'department': convert_to_regexp('Procurement')},
            {'title': convert_to_regexp('Supply Chain')},
            {'department': convert_to_regexp('Supply Chain')},
            {'title': convert_to_regexp('Finance')},
            {'department': convert_to_regexp('Finance')},
            {'title': convert_to_regexp('Contracts')},
            {'department': convert_to_regexp('Contracts')},
            {'title': convert_to_regexp('Vendor')},
            {'department': convert_to_regexp('Vendor')}
        ],
    },
{
        '$or': [
            {'title': convert_to_regexp('Fire')},
            {'department': convert_to_regexp('Fire')},
            {'title': convert_to_regexp('Rescue')},
            {'department': convert_to_regexp('Rescue')},
            {'title': convert_to_regexp('Firefighter')},
            {'department': convert_to_regexp('Firefighter')},
            {'title': convert_to_regexp('Fire Marshal')},
            {'department': convert_to_regexp('Fire Marshal')},
            {'title': convert_to_regexp('EMT')},
            {'department': convert_to_regexp('EMT')},
            {'title': convert_to_regexp('Paramedic')},
            {'department': convert_to_regexp('Paramedic')}
        ],
    },
{
        '$or': [
            {'title': convert_to_regexp('Economic')},
            {'department': convert_to_regexp('Economic')},
            {'title': convert_to_regexp('Business Development')},
            {'department': convert_to_regexp('Business Development')},
            {'title': convert_to_regexp('Investment')},
            {'department': convert_to_regexp('Investment')},
            {'title': convert_to_regexp('Trade')},
            {'department': convert_to_regexp('Trade')},
            {'title': convert_to_regexp('Urban Planner')},
            {'department': convert_to_regexp('Urban Planner')},
            {'title': convert_to_regexp('Commerce')},
            {'department': convert_to_regexp('Commerce')},
        ],
    },
{
        '$or': [
            {'title': convert_to_regexp('Water')},
            {'department': convert_to_regexp('Water')},
            {'title': convert_to_regexp('Sewage')},
            {'department': convert_to_regexp('Sewage')},
            {'title': convert_to_regexp('Energy')},
            {'department': convert_to_regexp('Energy')},
            {'title': convert_to_regexp('Wastewater')},
            {'department': convert_to_regexp('Wastewater')},
            {'title': convert_to_regexp('Waste')},
            {'department': convert_to_regexp('Waste')},
        ],
    },
{
        '$or': [
            {'title': convert_to_regexp('Finance')},
            {'department': convert_to_regexp('Finance')},
            {'title': convert_to_regexp('Financial')},
            {'department': convert_to_regexp('Financial')},
            {'title': convert_to_regexp('Treasurer')},
            {'department': convert_to_regexp('Treasurer')},
            {'title': convert_to_regexp('Budget')},
            {'department': convert_to_regexp('Budget')},
            {'title': convert_to_regexp('Accountant')},
            {'department': convert_to_regexp('Accountant')},
            {'title': convert_to_regexp('Audit')},
            {'department': convert_to_regexp('Audit')},
            {'title': convert_to_regexp('Auditor')},
            {'department': convert_to_regexp('Auditor')},
            {'title': convert_to_regexp('Payable')},
            {'department': convert_to_regexp('Payable')},
            {'title': convert_to_regexp('Receivable')},
            {'department': convert_to_regexp('Receivable')},
            {'title': convert_to_regexp('Revenue')},
            {'department': convert_to_regexp('Revenue')},
            {'title': convert_to_regexp('Tax')},
            {'department': convert_to_regexp('Tax')},
            {'title': convert_to_regexp('Business')},
            {'department': convert_to_regexp('Business')},
        ],
    },
{
        '$or': [
            {'title': convert_to_regexp('Geographic Information System')},
            {'department': convert_to_regexp('Geographic Information System')},
            {'title': convert_to_regexp('Cartographer')},
            {'department': convert_to_regexp('Cartographer')},
            {'title': convert_to_regexp('Spatial')},
            {'department': convert_to_regexp('Spatial')},
            {'title': convert_to_regexp('GIS')},
            {'department': convert_to_regexp('GIS')},
        ],
    },
{
        '$or': [
            {'title': convert_to_regexp('Human Resources')},
            {'title': convert_to_regexp('HR')},
            {'title': convert_to_regexp('Recruitment')},
            {'title': convert_to_regexp('Benefits')},
            {'title': convert_to_regexp('Training and Development')},
            {'title': convert_to_regexp('Talent')},
            {'title': convert_to_regexp('Employee Relations')},
            {'title': convert_to_regexp('Payroll')},
            {'title': convert_to_regexp('Benefits')},
            {'department': convert_to_regexp('Human Resources')},
            {'department': convert_to_regexp(' HR')},
            {'department': convert_to_regexp('Recruitment')},
            {'department': convert_to_regexp('Benefits')},
            {'department': convert_to_regexp('Training and Development')},
            {'department': convert_to_regexp('Talent')},
            {'department': convert_to_regexp('Employee Relations')},
            {'department': convert_to_regexp('Payroll')},
            {'department': convert_to_regexp('Benefits')},
        ],
    },
{
        '$or': [
            {'title': convert_to_regexp('Chief Information Officer')},
            {'department': convert_to_regexp('Chief Information Officer')},
            {'title': convert_to_regexp('IT')},
            {'department': convert_to_regexp('IT')},
            {'title': convert_to_regexp('Network')},
            {'department': convert_to_regexp('Network')},
            {'title': convert_to_regexp('Systems Analyst')},
            {'department': convert_to_regexp('Systems Analyst')},
            {'title': convert_to_regexp('Cybersecurity')},
            {'department': convert_to_regexp('Cybersecurity')},
            {'title': convert_to_regexp('Database Administrator')},
            {'department': convert_to_regexp('Database Administrator')},
            {'title': convert_to_regexp('Help Desk Technician')},
            {'department': convert_to_regexp('Help Desk Technician')},
            {'title': convert_to_regexp('Software Developer')},
            {'department': convert_to_regexp('Software Developer')},
            {'title': convert_to_regexp('IT Project Manager')},
            {'department': convert_to_regexp('IT Project Manager')},
            {'title': convert_to_regexp('Data')},
            {'department': convert_to_regexp('Data')},
            {'title': convert_to_regexp('GIS')},
            {'department': convert_to_regexp('GIS')},
            {'title': convert_to_regexp('IT Analyst')},
            {'department': convert_to_regexp('IT Analyst')},
            {'title': convert_to_regexp('Cyber')},
            {'department': convert_to_regexp('Cyber')},
            {'title': convert_to_regexp('Technology')},
            {'department': convert_to_regexp('Technology')},
        ],
    },
{
        '$or': [
            {'title': convert_to_regexp('Communications')},
            {'department': convert_to_regexp('Communications')},
            {'title': convert_to_regexp('Public Information')},
            {'department': convert_to_regexp('Public Information')},
            {'title': convert_to_regexp('Media')},
            {'department': convert_to_regexp('Media')},
            {'title': convert_to_regexp('Social Media')},
            {'department': convert_to_regexp('Social Media')},
            {'title': convert_to_regexp('Outreach')},
            {'department': convert_to_regexp('Outreach')},
            {'title': convert_to_regexp('Community Engagement')},
            {'department': convert_to_regexp('Community Engagement')},
            {'title': convert_to_regexp('Public Relations')},
            {'department': convert_to_regexp('Public Relations')},
        ],
    },
{
        '$or': [
            {'title': convert_to_regexp('Clerk')},
            {'department': convert_to_regexp('Clerk')},
            {'title': convert_to_regexp('County')},
            {'department': convert_to_regexp('County')},
            {'title': convert_to_regexp('Chief Administrative Officer')},
            {'department': convert_to_regexp('Chief Administrative Officer')},
            {'title': convert_to_regexp('Mayor')},
            {'department': convert_to_regexp('Mayor')},
            {'title': convert_to_regexp('Administration')},
            {'department': convert_to_regexp('Administration')},
            {'title': convert_to_regexp('Administer')},
            {'department': convert_to_regexp('Administer')},
            {'title': convert_to_regexp('City Manager')},
            {'department': convert_to_regexp('City Manager')},
            {'title': convert_to_regexp('Administrator')},
            {'department': convert_to_regexp('Administrator')},
        ],
    },
]}
# End of Selection
